### PR TITLE
Fixed thin_dump usage.

### PR DESCRIPTION
**Pull request by jcbertin**
Added support for recent thin_dump with --metadata-snap option.

### CODE REVIEW

**Comment by jcbertin** [comment]
This should fix Issue #51.

**Comment by tgmedia-nz** [comment]
will this get merged at some point?

**Comment by jcbertin** [comment]
Hope so!
On Tue, 2017-08-08 at 21:28 +0000, Thomas Gross wrote:
> will this get merged at some point?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Jean-Charles BERTIN
Axinoe - Software Engineer
Tel.: (+33) (0)1.80.82.59.23
Fax : (+33) (0)1.80.82.59.29
Skype: jcbertin
Web: <http://www.axinoe.com/>
Certificate Authority: <https://ca.axinoe.com/axinoe-root.crt>

**Comment by Harvie** [comment]
merge please :-)

**Comment by tomponline** [comment]
Can this be merged now?

**Pull request merged**
